#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# copy template folder
cp -r -n $SCRIPT_DIR/express-template/* _scripts/express-template/"."[!"."]* ./

# yarn
yarn add express body-parser
yarn add eslint --dev
