#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# copy template folder
cp -r -n $SCRIPT_DIR/next-template/*/.?* ./

# yarn
yarn add react react-dom next
yarn add eslint eslint-plugin-react --dev
